export const data = {
  name: "Ryan Lahlou",
  role: "Software Engineer",
  availability: "open",
  location: "Texas",
  email: "contact@ryanlahlou.com",
  image: "https://www.lryanle.com/assets/me.jpg",
  resume: "https://www.lryanle.com/resumes/RyanLahlouCR_06_20_24.pdf",
  experience: [
    {
      title: "MLH",
      image: "./mlhlogo.jpg",
      description: "Coach",
      role: "Coach",
      tags: ["0.5yoe"],
      href: "experience/mlh",
      duration: "0.5",
    },
    {
      title: "Meta",
      image: "./metalogo.png",
      description: "Software Engineer I",
      role: "Software Engineer I",
      tags: ["1yoe"],
      href: "/experience/meta",
      duration: "1",
    },
    {
      title: "Apple Inc",
      image: "./applelogo.png",
      description: "Junior Analyst",
      role: "Junior Analyst",
      tags: ["2yoe"],
      href: "/experience/apple",
      duration: "2",
    },
    {
      title: "Amazon LLC",
      image: "./amazonlogo.png",
      description: "Chief Executive Officer",
      role: "Chief Executive Officer",
      tags: ["23yoe"],
      href: "/experience/amazon",
      duration: "23",
    },
    {
      title: "Sanrio",
      image: "./sanriologo.png",
      description: "Software Engineer II",
      role: "Software Engineer II",
      tags: ["3yoe"],
      href: "/experience/sanrio",
      duration: "3",
    },
    {
      title: "Chipotle",
      image: "./chipotlelogo.png",
      description: "Jr Developer",
      role: "Jr Developer",
      tags: ["1yoe"],
      href: "/experience/chipotle",
      duration: "1",
    },
  ],
  education: [
    {
      image: "./umassamherstlogo.png",
      title: "University of Massachusetts Amherst",
      description: "Bachelor of Science in Computer Science",
      tags: ["Minor in Data Science", "Pres. of ACM"],
      href: "/education/umassamherst",
    },
    {
      image: "./mitlogo.png",
      title: "Massachusetts Institute of Technology",
      description: "Master of Science in Computer Science",
      tags: ["Concentrated in #6", "Pres. of Lettuce Club"],
      href: "/education/mit",
    }
  ],
  projects:[
    {
      image: "./nextjslogo.jpg",
      title: "NextJS Portfolio",
      description: "A gallery of my career in programming, built simply with Next.js",
      tags: ["Next.js", "shadcn/ui", "Tailwind", "React"],
      href: "/projects/portfolio",
    },
    {
      image: "./solidjslogo.png",
      title: "SolidJS Portfolio",
      description: "A gallery of my career in programming, built simply with SolidJS",
      tags: ["Solid.js", "shadcn/ui", "Tailwind", "React"],
      href: "/projects/portfolio",
    },
    {
      image: "./sveltejslogo.png",
      title: "SvelteJS Portfolio",
      description: "A gallery of my career in programming, built simply with SvelteJS",
      tags: ["Svelte.js", "shadcn/ui", "Tailwind", "React"],
      href: "/projects/portfolio",
    },
    {
      image: "./reactjslogo.png",
      title: "ReactJS Portfolio",
      description: "A gallery of my career in programming, built simply with ReactJS",
      tags: ["React.js", "shadcn/ui", "Tailwind", "React"],
      href: "/projects/portfolio",
    },
    {
      image: "./vuejslogo.png",
      title: "VueJS Portfolio",
      description: "A gallery of my career in programming, built simply with VueJS",
      tags: ["Vue.js", "shadcn/ui", "Tailwind", "React"],
      href: "/projects/portfolio",
    },
    {
      image: "./angularlogo.png",
      title: "Angular Portfolio",
      description: "A gallery of my career in programming, built simply with Angular",
      tags: ["Angular", "shadcn/ui", "Tailwind", "React"],
      href: "/projects/portfolio",
    },
  ]
}